---
title: "Ejercicios Módulo 3"
format: 
  live-html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    toc-location: left
    toc-title: Contenido
    code-copy: true
    code-overflow: wrap
filters:
  - webr-teachr
  - quiz-teachr
webr:
  pagkages: ["ggplot2", "dplyr"]
engine: knitr
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

::: {.callout-note}
## Nota
En los siguientes ejercicios se usan `{ggplot2}` y `{dplyr}` que están precargados en la página. No es necesario que cargues las librerías.
:::

## Ejercicios 3.1

**1. El operador de cascada de base de R es `|>`**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**2. Este es un buen nombre para un objeto en R: `conteo semanal`**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**3. Cuando digo que una tabla está en formato largo, puedo decir que es rectangular**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**4. `Z` es una función, `Y` es un objeto. Con la expresión `Y(Z)` estoy evaluando `Y` en función de `Z`**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**5. La tabla msleep del paquete `{ggplot2}` tiene 83 filas y 11 columnas**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**6. Estas expresiones dan el mismo resultado**

```r
msleep %>% 
  filter(order == "Primates" | sleep_total >= 10)

msleep %>% 
  filter(order == "Primates", sleep_total >= 10)
```

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

```{webr}
#| setup: true
#| exercise:
#|   - ex_a6
#|   - ex_a7
#|   - ex_a8
#|   - ex_a9
library(ggplot2)
library(dplyr)
```

```{webr}
#| exercise: ex_a6
# Puedes copiar y pegar el código aquí directamente. 
```


**7. Estas expresión filtra la tabla `iris` excluyendo la categoría `virginica` de la columna `Species`**

```r
iris %>% 
  filter(Species != "virginica")
```

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

```{webr}
#| exercise: ex_a7
# Puedes copiar y pegar el código aquí directamente. 
```

**8. Deseo calcular la suma de `Petal.Width` por `Species` de la tabla `iris`. ¿Es correcta la siguiente expresión?**

```r
iris %>% 
  filter(Species) %>%
  summarize(suma = sum())
```

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

```{webr}
#| exercise: ex_a8
# Puedes copiar y pegar el código aquí directamente. 
```

**9. ¿Cómo harías para que la tabla `iris` se vea de la siguiente manera?**

```r
	   largo.sepal ancho.sepal largo.petalo ancho.petalo  especies
1            5.1         3.5          1.4          0.2    setosa
2            4.9         3.0          1.4          0.2    setosa
3            4.7         3.2          1.3          0.2    setosa
4            4.6         3.1          1.5          0.2    setosa
5            5.0         3.6          1.4          0.2    setosa
```


:::: {.panel-tabset}

## Ejercicio



```{webr}
#| exercise: ex_a9
```

## Hints

::: { .hint exercise="ex_a9"}
Para cambiar el nombre y el orden de las columnas, puedes usar la función `select` de `{dplyr}`.
:::

## Solución

::: { .solution exercise="ex_a9" }
Una posible solución estará disponible pasada la clase
:::

:::