---
title: "Trabajo final"
---

::: {.callout-important}
**Lee detenidamente las siguientes instrucciones antes de llevar a cabo el trabajo final.**
:::

## Generalidades

Independientemente de la opción que escoja el estudiante, el trabajo final deberá ser presentado de la siguiente manera:

1.    En forma de un archivo .zip conteniendo el proyecto de RStudio con todos los scripts usados para renderizar el trabajo final. **No hace falta adjuntar los datos usados para el análisis**.

2.    El archivo final renderizado puede ser presentado en formatos .pdf, .docx o .html

3.    El plazo final para la entrega del trabajo a mi correo electrónico (mmorenozambrano@gmail.com) es el **30 de Noviembre, 23H59 hora de Ecuador**.


## Opciones de trabajo final

Para aprobar el curso, el estudiante tendrá la posibilidad de optar entre las siguientes opciones:

**Opción 1:**

Presentación de un reporte estadístico con datos del estudiante o citando la fuente de los mismos. La decisión de las metodologías estadísticas es completamente libre.


**Opción 2:**

Presentación de un reporte estadístico con datos que proporciono a continuación. El estudiante deberá seguir las instrucciones de metodologías estadísticas a usar.

## Datos para la opción 2

Deberás usar la tabla de datos `community-health-evaluation-dataset`

