---
title: "Introducción a la Estadística para Ciencias Biológicas con R"
format: html
lang: es
execute: 
  warning: false
  message: false
  error: false
---

## Anuncios

::: {.callout-important}
-   **14.09.2024:** Bienvenidos al curso! antes de comenzar, una de las mejores oportunidades de aprender más acerca de R, es atender a sus conferencias. Afortunadament la conferencia de [LatinR2024](https://latinr.org/){target="_blank"} está próxima a darse a cabo en Noviembre de este año.
<!-- Note that there are five types of callouts, including: -->
<!-- `note`, `warning`, `important`, `tip`, and `caution`. -->
:::


## Descripción del curso:

El presente curso de estadística tiene cómo propósito el dar un enfoque práctico de metodologías estadísticas comúnmente empleadas en el campo de la biología y la agricultura sin hacer mayor énfasis en teoría y resolución de problemas a mano como usualmente ocurre en el desenvolvimiento de contenidos de cursos tradicionales en estadística. En su lugar, el currículum aquí propuesto busca el dar una visión práctica a sus participantes de cómo los datos pueden ser analizados en base a un orden cronológico dentro de una investigación empezando por la definición de la pregunta objeto de esta, pasando por la decisión del diseño experimental más adecuado y finalizando con su correcto análisis e interpretación de los resultados. En mayor detalle, se abarcan además problemas comunes en el análisis de datos como lo son los análisis exploratorios de carácter formal tales como estadísticos descriptivos, patrones de pérdida de observaciones y visualizaciones; y aquellos de carácter operacional como la preparación y limpieza de datos, buenas prácticas de documentación y programación. Es por ello por lo que se alienta a los participantes a usar sus propios datos a la par de los ejemplos que se pondrán a disposición con el fin de aprovechar el carácter práctico del curso que incluye un comprensivo recorrido en el uso de R, el cual es al momento el lenguaje de programación estadística de mayor predilección en diversas ramas de las ciencias biológicas tanto en la academia como en la industria.

## Requisitos:

-   Computador con al menos 2 GB de RAM y **procesador de 64 bits**

## Duración:

20 horas de clase repartidas en 8 sesiones de 2 horas y media cada una, y

20 horas autónomo-prácticas, dando un total de

**40 horas**

## Modalidad:

100% Online

## Horario:

Sábados: 14, 21, 28 de Septiembre, 5, 19 y 26 de Octubre de 9H00 a 12H00

Unica clase entre semana: Jueves 17 de Octubre de 18H30 a 20H30


```{r}
#| echo: false

invisible(Sys.setlocale("LC_TIME", "es_ES.UTF-8"))
library(calendR)


calendR(year = 2024, month = 9,
        start = "M",
        special.days = c(14, 21, 28),
        special.col = "#bfe2f2",
        text = c("9H00 a 12H00", "9H00 a 12H00", "9H00 a 12H00"),
        text.pos = c(14, 21, 28),
        text.size = 2.5,
        text.col = "blue")

#| echo: false

calendR(year = 2024, month = 10,
        start = "M",
        special.days = c(5, 17, 19, 26),
        special.col = "#bfe2f2",
        text = c("9H00 a 12H00", "18H30 a 20H30", "9H00 a 12H00", "9H00 a 12H00"),
        text.pos = c(5,17,19,26),
        text.size = 2.5,
        text.col = "blue")
```

::: {.callout-note}
**No hay clase el Sábado 12 de Octubre debido al feriado.** La clase se recupera el 17 de 18H30 a 20H30. 
<!-- Note that there are five types of callouts, including: -->
<!-- `note`, `warning`, `important`, `tip`, and `caution`. -->
:::

## Contenidos del curso



+--------------------------------------------------------------------+----------------------------------------------------------+
| Módulo                                                             | Contenido                                                |
+====================================================================+==========================================================+
| Módulo 1: Generalidades e Introducción a R                         | 1.  Generalidades                                        |
|                                                                    |                                                          |
| Duración: 2 horas                                                  | 2.  Introducción a R                                     |
|                                                                    |                                                          |
|                                                                    | 3.  Tipos de datos en R                                  |
|                                                                    |                                                          |
|                                                                    | 4.  Operadores en R                                      |
|                                                                    |                                                          |
|                                                                    | 5.  Tipos de objetos en R                                |
|                                                                    |                                                          |
|                                                                    | 6.  Paquetes y librerías                                 |
|                                                                    |                                                          |
|                                                                    | 7.  Operaciones básicas                                  |
|                                                                    |                                                          |
|                                                                    | 8.  Operaciones estadísticas básicas                     |
|                                                                    |                                                          |
|                                                                    | 9.  Estadísticos descriptivos                            |
+--------------------------------------------------------------------+----------------------------------------------------------+
| Módulo 2: Proyectos en R y buenas prácticas de programación        | 1.  Proyectos en R                                       |
|                                                                    |                                                          |
| Duración: 0.5 horas                                                | 2.  Reglas básicas para programar y nombrar objetos en R |
|                                                                    |                                                          |
|                                                                    | 3.  Buenas prácticas de programación                     |
+--------------------------------------------------------------------+----------------------------------------------------------+
| Módulo 3: Introducción al `{tidyverse}`                            | 1.  Tipos de tablas                                      |
|                                                                    |                                                          |
| Duración: 2.5 horas                                                | 2.  Tidy data                                            |
|                                                                    |                                                          |
|                                                                    | 3.  El `{tidyverse}`                                     |
|                                                                    |                                                          |
|                                                                    | 4.  Importación y exportación de datos                   |
|                                                                    |                                                          |
|                                                                    | 5.  Operaciones con tablas de datos                      |
+--------------------------------------------------------------------+----------------------------------------------------------+
| Módulo 4: Visualización de datos con `{ggplot2}`                   | 1.  Funciones de `{ggplot2}`                             |
|                                                                    |                                                          |
| Duración: 2.5 horas                                                | 2.  Geometrías                                           |
|                                                                    |                                                          |
|                                                                    | 3.  Estéticas de geometrías                              |
|                                                                    |                                                          |
|                                                                    | 4.  Formato de figuras                                   |
|                                                                    |                                                          |
|                                                                    | 5.  Análisis Exploratorio                                |
+--------------------------------------------------------------------+----------------------------------------------------------+
| Módulo 5: Introducción a la Estadística Inferencial con R          | 1.  Muestras, poblaciones y muestreos                    |
|                                                                    |                                                          |
| Duración: 5 horas                                                  | 2.  Parámetros poblaciones y de muestro                  |
|                                                                    |                                                          |
|                                                                    | 3.  Estimación de parámetros de población.               |
|                                                                    |                                                          |
|                                                                    | 4.  Intervalos de confianza                              |
|                                                                    |                                                          |
|                                                                    | 5.  Pruebas de hipótesis                                 |
|                                                                    |                                                          |
|                                                                    | 6.  Tipos de errores                                     |
|                                                                    |                                                          |
|                                                                    | 7.  Poder de una prueba estadística                      |
|                                                                    |                                                          |
|                                                                    | 8.  Tamaño del efecto                                    |
|                                                                    |                                                          |
|                                                                    | 9.  Colas de una prueba                                  |
|                                                                    |                                                          |
|                                                                    | 10. Pruebas estadísticas paramétricas simples            |
|                                                                    |                                                          |
|                                                                    | 11. Pruebas estadísticas no paramétricas                 |
|                                                                    |                                                          |
|                                                                    | 12. Introducción al Análisis de Varianza (ANOVA)         |
+--------------------------------------------------------------------+----------------------------------------------------------+
| Módulo 6: Principios básicos de Diseño de Experimentos             | 1.  Tipos de estudios                                    |
|                                                                    |                                                          |
| Duración: 2.5 horas                                                | 2.  Pilares del diseño de experimentos                   |
|                                                                    |                                                          |
|                                                                    | 3.  Repeticiones                                         |
|                                                                    |                                                          |
|                                                                    | 4.  Tamaño de muestra                                    |
|                                                                    |                                                          |
|                                                                    | 5.  Diseño Completamente al Azar (DCA)                   |
|                                                                    |                                                          |
|                                                                    | 6.  Diseño en Bloques Completamente al Azar (DBCA)       |
|                                                                    |                                                          |
|                                                                    | 7.  Diseño Factorial Completo (DFC)                      |
|                                                                    |                                                          |
|                                                                    | 8.  Diseño Cuadrado Latino (DCL)                         |
|                                                                    |                                                          |
|                                                                    | 9.  Otros diseños experimentales                         |
+--------------------------------------------------------------------+----------------------------------------------------------+
| Módulo 7: Otros métodos estadísticos comúnmente usados en Biología | 1.  Regresión lineal simple y múltiple                   |
|                                                                    |                                                          |
| Duración: 3 horas                                                  | 2.  Introducción a modelos lineales generalizados        |
|                                                                    |                                                          |
|                                                                    | 3.  Análisis de componentes principales                  |
+--------------------------------------------------------------------+----------------------------------------------------------+
| Módulo 8: Introducción a la creación de reportes con Quarto        | 1.  Introducción a Quarto y Rmarkdown                    |
|                                                                    |                                                          |
| Duración: 2 horas                                                  | 2.  Estructura de un documento de Quarto                 |
|                                                                    |                                                          |
|                                                                    | 3.  Generación de nuestro primer reporte                 |
|                                                                    |                                                          |
|                                                                    | 4.  Tipos de documentos en Quarto                        |
+--------------------------------------------------------------------+----------------------------------------------------------+




## Objetivos de aprendizaje:

Al término del curso, el estudiante deberá ser capaz de:

-   Realizar operaciones básicas en R, tales como: cargar, modificar, limpiar y guardar tablas de datos.

-   Realizar gráficos de manera profesional usando R.

-   Planificar y decidir que tipo de diseño experimental deberá usar para llevar a cabo un estudio, dependiendo de la hipótesis del mismo.

-   Llevar a cabo análisis exploratorio de datos.

-   Llevar a cabo, interpretar y reportar los resultados de metodologías estadísticas tales como: pruebas t, pruebas no paramétricas y análisis de varianza.

-   Realizar reportes estadísticos básicos en R.

## Evaluación del curso

Para aprobar el curso, el estudiante tendrá la posibilidad de optar entre las siguientes opciones:

**Opción 1:**

Dos semanas antes del término de curso estará disponible en el servidor de Moodle una evaluación final de todo lo cubierto en los distintos módulos del mismo, abierta para su resolución hasta el 16 de Noviembre de 2024.

**Opción 2:**

Presentación de un reporte estadístico con datos del estudiante o citando la fuente de los mismos. La estructura de este tipo de reporte deberá seguir las instrucciones detalladas en el módulo del curso pertinente a la preparación y elaboración de reportes en R. La fecha límite de entrega de esta opción es hasta el 16 de Noviembre de 2024 a la dirección de correo del instructor.


## Canales de comunicación:

-   Preguntas durante las sesiones

-   Consultas dirigidas al instructor al correo electrónico: mmorenozambrano@gmail.com

## Sobre el instructor

Mauricio Moreno, PhD

Ingeniero en Biotecnología (Universidad de las Fuerzas Armadas - ESPE), cuenta con un máster en Estadística con mención en Biometría (KU Leuven, Bélgica) y un doctorado en Bioinformática (Jacobs University Bremen, Alemania), posee más de diez años de experiencia en programación estadística en R. Ha trabajado como consultor independiente, profesor, analista de estadísticas ambientales e investigador postdoctoral. Actualmente, ocupa el puesto de Científico Bioestadístico en la función de Soluciones de Campo en Bayer Crop Science, liderando proyectos de investigación y desarrollo incluyendo la migración de procesos estadísticos a la nube y determinación de tamaños de muestra mediante simulaciones Montecarlo basados en cadenas de Markov.


